services:

  cbos-api:

    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: cbos-api

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8090:8088"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/app:/app/app
      - ./frontend:/frontend
